export enum Color {
  COLOR_RED,
  COLOR_BLUE,
  COLOR_SWITCH,
  COLOR_GREEN,
  COLOR_YELLOW,
}

export const COLOR_STRINGS = {
  [Color.COLOR_RED]: "redCard",
  [Color.COLOR_BLUE]: "blueCard",
  [Color.COLOR_SWITCH]: "switchCard",
  [Color.COLOR_GREEN]: "greenCard",
  [Color.COLOR_YELLOW]: "yellowCard",
} as const;

export interface Card {
  color: (typeof COLOR_STRINGS)[Color];
  values: number[];
  selectedValue: number;
  leftOperation: null | (() => void);
  rightOperation: null | (() => void);
}

export const HOUSE_CARDS: Card[] = [
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [4],
    selectedValue: 4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [4],
    selectedValue: 4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [4],
    selectedValue: 4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [4],
    selectedValue: 4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [5],
    selectedValue: 5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [5],
    selectedValue: 5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [5],
    selectedValue: 5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [5],
    selectedValue: 5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [6],
    selectedValue: 6,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [6],
    selectedValue: 6,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [6],
    selectedValue: 6,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [6],
    selectedValue: 6,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [7],
    selectedValue: 7,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [7],
    selectedValue: 7,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [7],
    selectedValue: 7,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [7],
    selectedValue: 7,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [8],
    selectedValue: 8,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [8],
    selectedValue: 8,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [8],
    selectedValue: 8,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [8],
    selectedValue: 8,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [9],
    selectedValue: 9,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [9],
    selectedValue: 9,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [9],
    selectedValue: 9,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [9],
    selectedValue: 9,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [10],
    selectedValue: 10,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [10],
    selectedValue: 10,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [10],
    selectedValue: 10,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_GREEN],
    values: [10],
    selectedValue: 10,
    leftOperation: null,
    rightOperation: null,
  },
];

export const BLUE_CARDS: Card[] = [
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [4],
    selectedValue: 4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [5],
    selectedValue: 5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [6],
    selectedValue: 6,
    leftOperation: null,
    rightOperation: null,
  },
];

export const RED_CARDS: Card[] = [
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-1],
    selectedValue: -1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-2],
    selectedValue: -2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-3],
    selectedValue: -3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-4],
    selectedValue: -4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-5],
    selectedValue: -5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-6],
    selectedValue: -6,
    leftOperation: null,
    rightOperation: null,
  },
];

export const SWITCH_CARDS: Card[] = [
  {
    color: COLOR_STRINGS[Color.COLOR_SWITCH],
    values: [-1, 1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_SWITCH],
    values: [-2, 2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_SWITCH],
    values: [-3, 3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_SWITCH],
    values: [-4, 4],
    selectedValue: 4,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_SWITCH],
    values: [-5, 5],
    selectedValue: 5,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_SWITCH],
    values: [-6, 6],
    selectedValue: 6,
    leftOperation: null,
    rightOperation: null,
  },
];

// TODO: Add yellow card definitions

export const BASIC_OPPONENT_SIDE_DECK: Card[] = [
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [1],
    selectedValue: 1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-1],
    selectedValue: -1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-1],
    selectedValue: -1,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [2],
    selectedValue: 2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-2],
    selectedValue: -2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-2],
    selectedValue: -2,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_BLUE],
    values: [3],
    selectedValue: 3,
    leftOperation: null,
    rightOperation: null,
  },
  {
    color: COLOR_STRINGS[Color.COLOR_RED],
    values: [-3],
    selectedValue: -3,
    leftOperation: null,
    rightOperation: null,
  },
];
